### ISSUE TITLE
Babel example doesn't work

### ISSUE THREAD

**Issue by britter** [huston007/ng-annotate-loader#14]
I'm having trouble getting ng-annotate-loader to work together with babel-loader, so I tried the babel example.

After `npm install babel babel-loader` and then running `webpack` in the examples/babel folder I get:

```
$ webpack
Hash: d6b7d6bad8ca0746b6ec
Version: webpack 1.12.2
Time: 55ms
    + 1 hidden modules

ERROR in Cannot find module 'ng-annotate'
```

**Comment by huston007** [comment]
Sorry, but you did it wrong. Please run `npm install` on root and then `npm test`

**Comment by britter** [comment]
Thank you for the pointer, that did the trick.

**Comment by huston007** [comment]
@britter thank you for reporting, I'm going to put it into the readme.
