### ISSUE TITLE
Incorrect source mapping (again)

### ISSUE THREAD

**Issue by dgsmith2** [huston007/ng-annotate-loader#21]
I know this issue was addressed in #10, but I am seeing it again.

This issue also exists in ng-annotate-webpack-plugin (jeffling/ng-annotate-webpack-plugin#17)

**Comment by huston007** [comment]
@dgsmith2 source-map dependency has been updated in ng-annotate-loader@0.1.1. Could you please update ng-annotate-loader and check it again?

**Comment by dgsmith2** [comment]
Things are looking good now.  Thanks @huston007 .
