### ISSUE TITLE
Needs new release

### ISSUE THREAD

**Issue by deini** [huston007/ng-annotate-loader#22]
@huston007 Can you please release `0.1.1` to bring https://github.com/huston007/ng-annotate-loader/pull/19 changes which will fix: https://github.com/huston007/ng-annotate-loader/issues/20 and possibly https://github.com/huston007/ng-annotate-loader/issues/21 🙏

**Comment by huston007** [comment]
@deini Thank you for your reminder. OK let's do this)

**Comment by huston007** [comment]
Done

**Comment by deini** [comment]
Thank you @huston007
