### ISSUE TITLE
Plugin support

### ISSUE THREAD

**Issue by aikoven** [huston007/ng-annotate-loader#3]
First of all thank you for this loader, it's much more convenient than ng-annotate webpack plugin.

Could you please add support for ng-annotate plugins

```
ngAnnotate(src, {
    ...
    plugin: [somePlugin],
    ...
});
```
https://github.com/olov/ng-annotate#library-api

**Comment by huston007** [comment]
@aikoven Thanks. I will try)

**Comment by huston007** [comment]
@aikoven Fixed, please see [readme](https://github.com/huston007/ng-annotate-loader#using-ng-annotate-plugins)
